### ISSUE TITLE
GNOME 44 Support

### ISSUE THREAD

**Issue by git-Hmmm** [mackdk/gnome-github-manager#1]
Please add support for GNOME 44 to ensure compatibility with the latest version of GNOME and provide users with access to new features and improvements.

I had a question:
Do you have any plans to publish this on GNOME Extensions?
As original developer no longer maintaining this.

**Comment by mackdk** [comment]
Hi. 

Yes, I would like to add support for GNOME 44, but at the moment I have no way to test it as I develop on GNOME 41 and I have a secondary laptop still on 43. I will try to see if I can update it to 44 and check if everything is still working.

> Do you have any plans to publish this on GNOME Extensions?

Short answer is yes, but I don't have a time frame for that. This is mostly a thing that I started for myself to learn Typescript. The extension is still under *heavy* but **very slow** development, as I have yet to implement what I actually wanted to add and I work on it only in my free time.
